### PR TITLE
Placement new

### PR DESCRIPTION
**Pull request by AlexanderSaydakov**

### CODE REVIEW

**Comment by jmalkin** [comment]
Not obvious what gcc doesn't like about those tests, but removing those means we have no clue if any of this code is internally consistent or consistent with java's handling of inputs. So that's very bad.

The placement new changes are good.

**Comment by AlexanderSaydakov** [comment]
We need to get back to these tests to see what we can restore, and what we should remove.

**Comment by jmalkin** [comment]
The HLL unit tests were only using the public API. That the code didn't compile under gcc means that there's an actual issue. It shows up with the python wrapper, too.

**Comment by AlexanderSaydakov** [comment]
@jmalkin I see you restored the branch. Do we need it?

**Comment by jmalkin** [comment]
I re-opened since once of the tests that was disabled really needed to be there, but that wasn't really the right way to handle the issue after the branch was already merged. And subsequent work (immediately after) fixed the underlying issue,

**Pull request merged**
